import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/layouts/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`} suppressHydrationWarning>
        {/* Navbar  */}
        <NavBar />

        {/* Content */}
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
